fix: Requested by @Aprillion  #54
OpenSourceRaidGuild/website pull request #55
Opened 2021-01-26 19:56 UTC by AhmedEldessouki

2021-01-26 19:57 UTC, AhmedEldessouki commented
resolves #54

2021-01-26 20:03 UTC, AhmedEldessouki commented
```
husky > pre-commit (node v14.15.4)
[STARTED] Preparing...
[SUCCESS] Preparing...
[STARTED] Running tasks...
[STARTED] Running tasks for *.+(js|jsx|ts|tsx)
[STARTED] Running tasks for *.+(json|yml|yaml|css)
[STARTED] yarn lint:precomit
[SUCCESS] prettier --write
[SUCCESS] Running tasks for *.+(json|yml|yaml|css)
[SUCCESS] yarn lint:precomit
[SUCCESS] Running tasks for *.+(js|jsx|ts|tsx)
[SUCCESS] Running tasks...
[STARTED] Applying modifications...
[SUCCESS] Applying modifications...
[STARTED] Cleaning up...
[SUCCESS] Cleaning up...
```

2021-01-26 20:07 UTC, AhmedEldessouki commented
@JacobMGEvans should i keep it that (with the new script) or remove the new script?

2021-01-26 21:54 UTC, JacobMGEvans requested changes

2021-01-26 21:54 UTC, JacobMGEvans commented on lint-staged.config.js
> +  // '*.+(js|jsx|ts|tsx)': ['yarn lP:precommit', 'yarn test:precommit'],
```suggestion
```

2021-01-27 11:40 UTC, merodiro commented
This would revert the changes I made to speed pre-commit hook in #56

also there is no need to run both `yarn lint` and `yarn format` because `eslint` will run `prettier` with this `plugin:prettier/recommended` in the config

2021-01-27 12:07 UTC, AhmedEldessouki commented
> 
> 
> This would revert the changes I made to speed pre-commit hook in #56
> 
> also there is no need to run both `yarn lint` and `yarn format` because `eslint` will run `prettier` with this `plugin:prettier/recommended` in the config

interesting i didnt know that. ok i will do the changes

2021-01-27 16:58 UTC, merodiro reviewed
Running `yarn lint` is slower than running `eslint --fix` because it would run eslint on every file in the repo and not just the changed files. you can check #56 for the numbers

2021-01-27 19:37 UTC, AhmedEldessouki commented
@JacobMGEvans @merodiro 
 one of the CI `windows latest, 14` failed at installing dependencies (firebase). and that's what i am using and running yarn doesn't give any errors. what shall i do?

2021-01-28 00:17 UTC, JacobMGEvans approved these changes

2021-01-28 00:18 UTC, merged